// <auto-generated />
using System;
using BAMS_backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BAMS_backend.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20251213172135_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BAMS_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bams.com",
                            FirstName = "Admin",
                            IsApproved = true,
                            LastName = "Ryan",
                            PasswordHash = "$2a$11$uY4zfr1p4nbksd4Sy4cn0.LTc44mHE41Sod5CKn9Wc65vBdvU/mA.",
                            Phone = "",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "coach@bams.com",
                            FirstName = "Head",
                            IsApproved = true,
                            LastName = "Coach",
                            PasswordHash = "$2a$11$uY4zfr1p4nbksd4Sy4cn0.LTc44mHE41Sod5CKn9Wc65vBdvU/mA.",
                            Phone = "",
                            Role = "Coach"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "player@bams.com",
                            FirstName = "Team",
                            IsApproved = false,
                            LastName = "Player",
                            PasswordHash = "$2a$11$uY4zfr1p4nbksd4Sy4cn0.LTc44mHE41Sod5CKn9Wc65vBdvU/mA.",
                            Phone = "",
                            Role = "Player"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "parent@bams.com",
                            FirstName = "Guardian",
                            IsApproved = true,
                            LastName = "Parent",
                            PasswordHash = "$2a$11$uY4zfr1p4nbksd4Sy4cn0.LTc44mHE41Sod5CKn9Wc65vBdvU/mA.",
                            Phone = "",
                            Role = "Parent"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
